baseUrl: https://kubecost.example.com
apiToken: ""
defaultWindow: 30d
timeout: 15s
tlsSkipVerify: false

# Prediction API specific configuration
clusterId: your-cluster-id
defaultNamespace: default
predictionWindow: 2d
